### ISSUE TITLE
Documentation: deploy and link in README.md

### ISSUE THREAD

**Issue by rouson** [sourceryinstitute/julienne#11]
The  "documentation" link in the [README.md] currently points to the Assert documentation.  Replacing "assert" with "julienne" in the corresponding URL generates a 404 error.

### To Do
- [x] Verify whether the CI is generating and deploying documentation.
- [x] Update the URL in the hyperlinked "documentation" text in the README.md accordingly.

[README.md]: https://github.com/sourceryinstitute/julienne/blob/7de187d7001bd08d60faf3fc594b98e7c997f65c/README.md

**Comment by ktras** [comment]
In the `Settings` tab of the repo, the `Pages` section needed to be updated to be able to have a place for the deployed documentation to land. This has now been updated and then PR #13 updates the link the README.
